const MusicDataActionTypes = {
  FETCH_MUSIC_DATA_START: "FETCH_MUSIC_DATA_START",
  FETCH_MUSIC_DATA_SUCCESS: "FETCH_MUSIC_DATA_SUCCESS",
  FETCH_MUSIC_DATA_FAILURE: "FETCH_MUSIC_DATA_FAILURE",
};

export default MusicDataActionTypes;
